[package]
name = "mingaurm/noisepp"
version = "1.0.0"
description = "A noise module that adds noise types and features that the math.noise function doesn't have."
license = "None"
authors = ["Miguel Rossetti Mocellin"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["rokit.toml", "selene.toml"]

[dependencies]
